baseURL = "https://jozefrebjak.com/"
defaultContentLanguage = "en"
enableRobotsTXT = true
enableGitInfo = true
enableEmoji = true
theme = "CodeIT"

[languages]
  [languages.en]
    weight = 1
    title = "Jozef Rebjak"
    languageCode = "en"
    languageName = "English"
    copyright = "This work is licensed under a Creative Commons Attribution-NonCommercial 4.0 International License."
    [[languages.en.menu.main]]
      identifier = "posts"
      pre = ""
      post = ""
      name = "Posts"
      url = "/posts/"
      title = ""
      weight = 1
    [[languages.en.menu.main]]
      identifier = "tags"
      pre = ""
      post = ""
      name = "Tags"
      url = "/tags/"
      title = ""
      weight = 2
    [[languages.en.menu.main]]
      identifier = "categories"
      pre = ""
      post = ""
      name = "Categories"
      url = "/categories/"
      title = ""
      weight = 3
    [[languages.en.menu.main]]
      identifier = "github"
      pre = "<i class='fab fa-github fa-fw'></i>"
      post = ""
      name = ""
      url = "https://github.com/jozefrebjak"
      title = "GitHub"
      weight = 4
    [languages.en.params]
      # site description
      description = "Jozef Rebjak's personal website about open-source software including databases, operating systems, containers, and middleware as well as open-source tools for analytics, virtualization, and development in technology."
      # site keywords
      keywords = ["Jozef Rebjak", "Hugo", "IT", "Blog"]
      # App icon config
      [languages.en.params.app]
        # optional site title override for the app when added to an iOS home screen or Android launcher
        title = "Jozef Rebjak's personal website"
        # whether to omit favicon resource links
        noFavicon = false
        # modern SVG favicon to use in place of older style .png and .ico files
        svgFavicon = ""
        # Android browser theme color
        themeColor = "#ffffff"
        # Safari mask icon color
        iconColor = "#5bbad5"
        # Windows v8-10 tile color
        tileColor = "#da532c"
      # Search config
      [languages.en.params.search]
        enable = true
        # type of search engine ("lunr", "algolia")
        type = "lunr"
        # max index length of the chunked content
        contentLength = 4000
        # placeholder of the search bar
        placeholder = ""
        # max number of results length
        maxResultLength = 10
        # snippet length of the result
        snippetLength = 30
        # HTML tag name of the highlight part in results
        highlightTag = "em"
        # whether to use the absolute URL based on the baseURL in search index
        absoluteURL = false
      # Home page config
      [languages.en.params.home]
        # amount of RSS pages
        rss = 10
        # Home page profile
        [languages.en.params.home.profile]
          enable = true
          # Gravatar Email for preferred avatar in home page
          gravatarEmail = ""
          # URL of avatar shown in home page
          avatarURL = "/images/avatar.svg"
          # title shown in home page (HTML format is supported)
          title = ""
          # subtitle shown in home page
          subtitle = "Just another IT blog, but really useful."
          # whether to use typeit animation for subtitle
          typeit = true
          # whether to show social links
          social = true
          # disclaimer (HTML format is supported)
          disclaimer = ""
        # Home page posts
        [languages.en.params.home.posts]
          enable = true
          # special amount of posts in each home posts page
          paginate = 6
  [languages.sk]
    weight = 2
    title = "Jozef Rebjak"
    languageCode = "sk"
    languageName = "Slovensky"
    [[languages.sk.menu.main]]
      identifier = "posts"
      pre = ""
      post = ""
      name = "Príspevky"
      url = "/posts/"
      title = ""
      weight = 1
    [[languages.sk.menu.main]]
      identifier = "tags"
      pre = ""
      post = ""
      name = "Značky"
      url = "/tags/"
      title = ""
      weight = 2
    [[languages.sk.menu.main]]
      identifier = "categories"
      pre = ""
      post = ""
      name = "Kategórie"
      url = "/categories/"
      title = ""
      weight = 3
    [[languages.sk.menu.main]]
      identifier = "github"
      pre = "<i class='fab fa-github fa-fw'></i>"
      post = ""
      name = ""
      url = "https://github.com/jozefrebjak"
      title = "GitHub"
      weight = 4
    [languages.sk.params]
      # site description
      description = "Osobná webová stránka Jozefa Rebjaka o open-source softvéri vrátane databáz, operačných systémov, kontajnerov a middleware, ako aj o open-source nástrojoch na analýzu, virtualizáciu a technologický vývoj."
      # site keywords
      keywords = ["Jozef Rebjak", "Hugo", "IT", "Blog"]
      # App icon config
      [languages.sk.params.app]
        # optional site title override for the app when added to an iOS home screen or Android launcher
        title = "Osobná webová stránka Jozefa Rebjaka"
        # whether to omit favicon resource links
        noFavicon = false
        # modern SVG favicon to use in place of older style .png and .ico files
        svgFavicon = ""
        # Android browser theme color
        themeColor = "#ffffff"
        # Safari mask icon color
        iconColor = "#5bbad5"
        # Windows v8-10 tile color
        tileColor = "#da532c"
      # Search config
      [languages.sk.params.search]
        enable = true
        # type of search engine ("lunr", "algolia")
        type = "lunr"
        # max index length of the chunked content
        contentLength = 4000
        # placeholder of the search bar
        placeholder = ""
        # max number of results length
        maxResultLength = 10
        # snippet length of the result
        snippetLength = 30
        # HTML tag name of the highlight part in results
        highlightTag = "em"
        # whether to use the absolute URL based on the baseURL in search index
        absoluteURL = false
      # Home page config
      [languages.sk.params.home]
        # amount of RSS pages
        rss = 10
        # Home page profile
        [languages.sk.params.home.profile]
          enable = true
          # Gravatar Email for preferred avatar in home page
          gravatarEmail = ""
          # URL of avatar shown in home page
          avatarURL = "/images/avatar.png"
          # title shown in home page (HTML format is supported)
          title = ""
          # subtitle shown in home page
          subtitle = "Iba ďalší IT blog, ale naozaj užitočný."
          # whether to use typeit animation for subtitle
          typeit = true
          # whether to show social links
          social = true
          # disclaimer (HTML format is supported)
          disclaimer = ""
        # Home page posts
        [languages.sk.params.home.posts]
          enable = true
          # special amount of posts in each home posts page
          paginate = 6

[params]
  # CodeIT theme version
  version = "0.2.X"
  # site default theme ("light", "dark", "auto")
  defaultTheme = "auto"
  # public git repo url only then enableGitInfo is true
  gitRepo = "https://github.com/jozefrebjak/jozefrebjak.com"
  #  date format
  dateFormat = "02-01-2006"
  # website images for Open Graph and Twitter Cards
  images = ["/images/avatar.svg"]

  # Header config
  [params.header]
    # desktop header mode ("fixed", "normal", "auto")
    desktopMode = "fixed"
    # mobile header mode ("fixed", "normal", "auto")
    mobileMode = "auto"
    #  Header title config
    [params.header.title]
      # URL of the LOGO
      logo = ""
      # title name
      name = "Jozef Rebjak"
      # you can add extra information before the name (HTML format is supported), such as icons
      pre = "<i class='fas fa-terminal fa-fw'></i> "
      # you can add extra information after the name (HTML format is supported), such as icons
      post = ""
      #  whether to use typeit animation for title name
      typeit = false

  # Footer config
  [params.footer]
    enable = true
    #  whether to show Hugo and theme info
    hugo = true
    #  whether to show copyright info
    copyright = true
    #  whether to show the author
    author = true
    # Site creation time
    since = 2021
    # license info (HTML format is supported)
    license= '<a rel="license external nofollow noopener noreferrer" href="https://creativecommons.org/licenses/by-nc/4.0/" target="_blank">CC BY-NC 4.0</a>'

  #  Section (all posts) page config
  [params.section]
    # special amount of posts in each section page
    paginate = 20
    # date format (day and month)
    dateFormat = "02-01"
    # amount of RSS pages
    rss = 10

  #  List (category or tag) page config
  [params.list]
    # special amount of posts in each list page
    paginate = 20
    # date format (day and month)
    dateFormat = "02-01"
    # amount of RSS pages
    rss = 10

  # Home page config
  [params.home]
    #  amount of RSS pages
    rss = 10

  # Social config about the author
  [params.social]
    GitHub = "jozefrebjak"
    Linkedin = "jozefrebjak"
    Telegram = "jozefrebjak"
    Email = "jozerebjak@icloud.com"
    RSS = true

  #  Page config
  [params.page]
    #  whether to hide a page from home page
    hiddenFromHomePage = false
    #  whether to hide a page from search results
    hiddenFromSearch = false
    #  whether to enable twemoji
    twemoji = false
    # whether to enable lightgallery
    lightgallery = true
    #  whether to enable the ruby extended syntax
    ruby = true
    #  whether to enable the fraction extended syntax
    fraction = true
    #  whether to enable the fontawesome extended syntax
    fontawesome = true
    # whether to show link to Raw Markdown content of the content
    linkToMarkdown = false
    #  whether to show the full text content in RSS
    rssFullText = false
    #  Table of the contents config
    [params.page.toc]
      # whether to enable the table of the contents
      enable = true
      #  whether to keep the static table of the contents in front of the post
      keepStatic = true
      # whether to make the table of the contents in the sidebar automatically collapsed
      auto = true
    #  Code config
    [params.page.code]
      # whether to show the copy button of the code block
      copy = true
      # the maximum number of lines of displayed code by default
      maxShownLines = 10
    [params.page.share]
      enable = true
      Facebook = true
      Linkedin = true
    # Comment config
    [params.page.comment]
      enable = true
      [params.page.comment.utterances]
        enable = true
        repo = "jozefrebjak/comments"
        issueTerm = "pathname"
        label = "Comment"
        lightTheme = "github-light"
        darkTheme = "photon-dark"
  #  TypeIt config
  [params.typeit]
    # typing speed between each step (measured in milliseconds)
    speed = 100
    # blinking speed of the cursor (measured in milliseconds)
    cursorSpeed = 1000
    # character used for the cursor (HTML format is supported)
    cursorChar = "|"
    # cursor duration after typing finishing (measured in milliseconds, "-1" means unlimited)
    duration = -1

  # Analytics config
  [params.analytics]
    enable = true
    [params.analytics.google]
      id = "G-XEGDBQE4ZL"
      # whether to anonymize IP
      anonymizeIP = true

  #  Compatibility config
  [params.compatibility]
    # whether to use Polyfill.io to be compatible with older browsers
    polyfill = false
    # whether to use object-fit-images to be compatible with older browsers
    objectFit = false

# Markup related config in Hugo
[markup]
  # Syntax Highlighting
  [markup.highlight]
    codeFences = true
    guessSyntax = true
    lineNos = true
    lineNumbersInTable = true
    # false is a necessary configuration
    noClasses = false
  # Goldmark is from Hugo 0.60 the default library used for Markdown
  [markup.goldmark]
    [markup.goldmark.extensions]
      definitionList = true
      footnote = true
      linkify = true
      strikethrough = true
      table = true
      taskList = true
      typographer = true
    [markup.goldmark.renderer]
      # whether to use HTML tags directly in the document
      unsafe = true
  # Table Of Contents settings
  [markup.tableOfContents]
    startLevel = 2
    endLevel = 6

# Author config
[author]
  name = "Jozef Rebjak"
  email = "jozefrebjak@icloud.com"

# Sitemap config
[sitemap]
  changefreq = "weekly"
  filename = "sitemap.xml"
  priority = 0.5

# Permalinks config
[Permalinks]
  # posts = ":year/:month/:filename"
  posts = ":filename"

# Options to make output .md files
[mediaTypes]
  [mediaTypes."text/plain"]
    suffixes = ["md"]

# Options to make output .md files
[outputFormats.MarkDown]
  mediaType = "text/plain"
  isPlainText = true
  isHTML = false

# Options to make hugo output files
[outputs]
  #
  home = ["HTML", "RSS", "JSON"]
  page = ["HTML", "MarkDown"]
  section = ["HTML", "RSS"]
  taxonomy = ["HTML", "RSS"]
  taxonomyTerm = ["HTML"]
